version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_api
      - POSTGRES_USER=mati
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_api
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_port=3306
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - PMA_HOST=mysql

volumes:
  postgres_data:

  mysql_data: